[package]
name = "dns-resolver-recommender"
version = "0.1.0"
edition = "2024"
authors = [
    "Jhannes Reimann <jhannes.reimann@student.hpi.uni-potsdam.de>",
    "Robert Richter <robert.richter@hpi.de"
]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64-url = "3.0.3"
futures = "0.3.32"
getrandom = { version = "0.2", features = ["js"] }
getrandom_04 = { package = "getrandom", version = "0.4.2", features = ["wasm_js"] }
hickory-proto = "0.26.1"
js-sys = "0.3.98"
rand = "0.8"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.71"
web-sys = { version = "0.3.98", features = ["AbortController", "AbortSignal", "Headers", "Performance", "Request", "RequestCredentials", "RequestInit", "RequestMode", "Response", "Window"] }
